Changefeedsperclient
schwamster/doc-store pull request #10
Opened 2016-12-15 00:15 UTC by andreimcristof

This pull request resolves issue nr 6 ( https://github.com/schwamster/doc-store/issues/6 , not exactly sure how do I link the task directly to a pull request) 

Next stop for me - notifications api gets a notif that the DB changed, then pushes that to the frontend, which updates automagically with new documents

2016-12-15 08:52 UTC, schwamster requested changes
see comments

2016-12-15 08:52 UTC, schwamster commented on src/doc-store/Store/Document.cs
> +            this.Client =  document.Client ?? "1337";
maybe use a constant for the default since u use it multiple times - easier to get rid of it later

2016-12-15 08:52 UTC, schwamster commented on src/doc-store/Store/IRethinkStore.cs
> +                LimitWatchToClient = "1337"
see comment above

2016-12-15 22:04 UTC, andreimcristof commented
adjusted; please see changes

2016-12-16 05:41 UTC, schwamster reviewed
nice

2016-12-16 05:41 UTC, schwamster approved these changes

2016-12-16 05:42 UTC, merged